// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBus4MQurimGCmvnUSFFAYR3D5VN2ZyrLg',
    appId: '1:790058877029:web:c7b39dc25ff7714a44868c',
    messagingSenderId: '790058877029',
    projectId: 'adas-cfb74',
    authDomain: 'adas-cfb74.firebaseapp.com',
    storageBucket: 'adas-cfb74.firebasestorage.app',
    measurementId: 'G-85MW1321E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsv7banMjajjja5Uozoy5GZQ3QyKL9LZU',
    appId: '1:790058877029:android:90b25cb0b380ea3044868c',
    messagingSenderId: '790058877029',
    projectId: 'adas-cfb74',
    storageBucket: 'adas-cfb74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnnSBgWPc8EYO1DHnSCxFSShcwWLHAiRc',
    appId: '1:790058877029:ios:1c1b32cc09e3dfdb44868c',
    messagingSenderId: '790058877029',
    projectId: 'adas-cfb74',
    storageBucket: 'adas-cfb74.firebasestorage.app',
    iosBundleId: 'com.example.adasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnnSBgWPc8EYO1DHnSCxFSShcwWLHAiRc',
    appId: '1:790058877029:ios:1c1b32cc09e3dfdb44868c',
    messagingSenderId: '790058877029',
    projectId: 'adas-cfb74',
    storageBucket: 'adas-cfb74.firebasestorage.app',
    iosBundleId: 'com.example.adasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBus4MQurimGCmvnUSFFAYR3D5VN2ZyrLg',
    appId: '1:790058877029:web:f138eba43796445144868c',
    messagingSenderId: '790058877029',
    projectId: 'adas-cfb74',
    authDomain: 'adas-cfb74.firebaseapp.com',
    storageBucket: 'adas-cfb74.firebasestorage.app',
    measurementId: 'G-V1DH3GXCKE',
  );
}
